name: Infrastructure Deployment


on:
  workflow_dispatch:
  push:
    branches:
     - master

permissions:
  id-token: write
  contents: read


jobs:
  deployment:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      #----------------------------------------------
      # ----- Authenticate With AWS Credentials -----
      #----------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #----------------------------------------------
      # --- Setup Terraform with specific version ---
      #----------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9
          terraform_wrapper: false

      - name: View versions of tools
        run: |
          echo "Terraform version: $(terraform version)"

    #----------------------------------------------
    #----  Setup Infrastructure   -----------------
    #----------------------------------------------
      - name: Setup Cloudfront S3 CDN Infrastructure
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: |
          cd terraform
          terraform init -backend-config=backend.hcl
      - name: Terraform validate
        run: |
          cd terraform
          terraform validate
      - name: Terraform plan
        run: |
          cd terraform
          terraform plan
      - name: Terraform apply
        run: |
          cd terraform
          terraform apply -auto-approve
      - name: Get Bucket Name
        run: |
          cd terraform
          # Get the S3 Bucket Name from terraform output
          S3_BUCKET_NAME=$(terraform output s3_bucket_name | tr -d '"')
          # Clean the output by removing any unwanted characters
          S3_BUCKET_NAME=$(echo "$S3_BUCKET_NAME" | sed 's/[^A-Za-z0-9_-]//g')
          # Export the bucket name variable to the environment for later use
          echo "S3_BUCKET_NAME=${S3_BUCKET_NAME}" >> $GITHUB_ENV
        shell: bash


    #------------------------------------------------------------------
    # ---------- Install Packages and Build Artifact ------------------
    #------------------------------------------------------------------

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Packages and Build Artifact
        run: |
          cd app
          npm install
          npm run build
        shell: bash

    #------------------------------------------------------------------
    # ----- Upload Artifact to S3 Bucket for specific environment -----
    #------------------------------------------------------------------
      - name: Upload Artifact to S3 Bucket
        run: |
          cd app/build
          # Sync the build directory to the S3 bucket
          aws s3 sync . s3://${{env.S3_BUCKET_NAME}} --delete
        shell: bash
  
    #----------------------------------------------
    #-------Deploy App to S3 Bucket----------------
    #-------Invalidate Cloudfront Distribution-----
    #----------------------------------------------

      - name: Terraform apply
        run: |
          cd terraform